import argparse
import shutil
import sys
from pathlib import Path

from push_to_whisper import __version__
from push_to_whisper.config import Settings


def serve_action(args):
    """Start the daemon (shortcut monitoring and recording)"""
    # Load at runtime only as dependencies like D-Bus occur during import
    from push_to_whisper.main_daemon import start_daemon

    settings = Settings.load(args.config)
    print(f"Starting Push-to-Whisper daemon (Config: {args.config or 'default'})...")
    start_daemon(settings)


def init_action(args):
    """Output a configuration file template"""
    import yaml

    from push_to_whisper.config import Settings
    from push_to_whisper.pipeline.state import PipelineState

    # Custom dump settings: Adjust to output strings in block format (|)
    def str_presenter(dumper, data):
        if len(data.splitlines()) > 1:  # check for multiline string
            return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
        return dumper.represent_scalar("tag:yaml.org,2002:str", data)

    yaml.add_representer(str, str_presenter)

    # Call Settings.load(ignore_config=True) to ignore existing configuration and output only default values
    if args.bare:
        settings = Settings.load(ignore_config=True)
    else:
        settings = Settings.load(args.config)

    # Convert Pydantic model to dictionary
    config_dict = settings.model_dump()
    yaml_text = yaml.dump(
        config_dict, default_flow_style=False, allow_unicode=True, sort_keys=False
    )

    # Generate a list of available template variables
    var_docs = "\n".join(
        [f"#   - {var:18} : {doc}" for var, doc in PipelineState.VARIABLE_DOCS.items()]
    )

    # Add help comments (considering indentation for each section)
    header = f"""# Push-to-Whisper Configuration Template
# Generated by Push-to-Whisper v{__version__}

# To enable LLM features, add the following steps to your pipeline in the 'pipelines' section:
# - type: llm_refine      # Refines the transcription for readability
# - type: llm_patch       # Automatically edits the Markdown (e.g., adds tags)
# - type: llm_instruction # Interprets the input as commands (Instruction Mode)

# Available Template Variables (for markdown_template and apprise templates):
{var_docs}

"""
    yaml_text = yaml_text.replace(
        "log_level: INFO",
        "# Log level (DEBUG, INFO, WARNING, ERROR)\nlog_level: INFO",
    )
    yaml_text = yaml_text.replace(
        "whisper:",
        "# Whisper Speech-to-Text Settings\nwhisper:",
    )
    yaml_text = yaml_text.replace(
        "  whisper_cpp:",
        "  # Local whisper.cpp server\n  # See: https://github.com/ggerganov/whisper.cpp/blob/master/examples/server/README.md\n  whisper_cpp:",
    )
    yaml_text = yaml_text.replace(
        "  openai:",
        "  # OpenAI-compatible API (OpenAI, Speaches, etc.)\n  openai:",
    )
    yaml_text = yaml_text.replace(
        "llm:",
        "# LLM Connection Settings (LiteLLM)\n# See: https://docs.litellm.ai/docs/providers\nllm:",
    )
    yaml_text = yaml_text.replace(
        "defaults:", "# Default options for each pipeline step type\ndefaults:"
    )
    yaml_text = yaml_text.replace(
        "  transcode:",
        "  # Transcode audio to other formats (requires ffmpeg)\n  transcode:",
    )
    yaml_text = yaml_text.replace(
        "  llm_refine:",
        "  # Refine transcription with a fixed prompt\n  llm_refine:",
    )
    yaml_text = yaml_text.replace(
        "  llm_instruction:",
        "  # Process transcription as a dynamic instruction\n  llm_instruction:",
    )
    yaml_text = yaml_text.replace(
        "  llm_patch:",
        "  # Edit the saved markdown file using LLM and udiff\n  llm_patch:",
    )
    yaml_text = yaml_text.replace(
        "  apprise:",
        "  # Send notifications via Apprise\n  # Examples: dbus:// (System notification), mailto://user:pass@gmail.com\n  # See: https://github.com/caronc/apprise\n  apprise:",
    )
    yaml_text = yaml_text.replace(
        "pipelines:", "# Define your custom workflows here\npipelines:"
    )

    final_output = header + yaml_text

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(final_output, encoding="utf-8")
        print(f"Created configuration template at: {out_path}")
    else:
        print(final_output)


def install_daemon_action(args):
    """Register and enable systemd user service and .desktop file"""
    import subprocess

    app_id = "com.github.likeablob.push-to-whisper"

    # 1. Create systemd service
    # Use app- prefix so that KDE/Portal can correctly identify the application
    service_name = f"app-{app_id}"
    user_systemd_dir = Path.home() / ".config/systemd/user"
    service_file = user_systemd_dir / f"{service_name}.service"

    # Resolve the path to the executable
    executable_path = shutil.which("push-to-whisper")
    if not executable_path:
        executable_path = f"{sys.executable} -m push_to_whisper.cli"

    # Identify the path to the virtual environment (two levels up from executable_path)
    venv_path = Path(executable_path).parent.parent if executable_path else None

    # Include config path in ExecStart if specified
    config_arg = f" -c {Path(args.config).absolute()}" if args.config else ""
    exec_start = f"{executable_path}{config_arg} serve"

    venv_env = f"Environment=VIRTUAL_ENV={venv_path.absolute()}" if venv_path else ""

    unit_content = f"""[Unit]
Description=Push-to-Whisper Daemon
After=network.target

[Service]
Type=simple
ExecStart={exec_start}
Restart=always
Environment=PYTHONUNBUFFERED=1
{venv_env}
# Setting to make KDE/Portal recognize the correct app name
Environment=DESKTOP_PORTAL_APP_ID={app_id}

[Install]
WantedBy=default.target
"""

    # 2. Create .desktop file (for display name in KDE settings screen)
    desktop_dir = Path.home() / ".local/share/applications"
    desktop_file = desktop_dir / f"{app_id}.desktop"

    desktop_content = f"""[Desktop Entry]
Type=Application
Name=Push to Whisper
Comment=Key-hold voice memos with Whisper
Exec={exec_start}
Icon=audio-input-microphone
Terminal=false
Categories=Utility;AudioVideo;
NoDisplay=true
"""

    try:
        # Save service
        user_systemd_dir.mkdir(parents=True, exist_ok=True)
        service_file.write_text(unit_content, encoding="utf-8")

        # Save .desktop file
        desktop_dir.mkdir(parents=True, exist_ok=True)
        desktop_file.write_text(desktop_content, encoding="utf-8")

        print(f"Created unit file: {service_file}")
        print(f"Created desktop file: {desktop_file}")

        subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
        subprocess.run(["systemctl", "--user", "enable", service_name], check=True)

        print(f"\nSuccessfully installed and enabled {service_name} service.")
        print(f"To start it now, run: systemctl --user start {service_name}")

    except Exception as e:
        print(f"Failed to install daemon: {e}")


def uninstall_daemon_action(args):
    """Stop and remove systemd user service and .desktop file"""
    import subprocess

    app_id = "com.github.likeablob.push-to-whisper"
    # Check both old and new names just in case
    service_names = [f"app-{app_id}", "app-push-to-whisper", "push-to-whisper"]
    user_systemd_dir = Path.home() / ".config/systemd/user"
    desktop_dir = Path.home() / ".local/share/applications"

    # Remove .desktop file
    desktop_file = desktop_dir / f"{app_id}.desktop"
    if desktop_file.exists():
        desktop_file.unlink()
        print(f"Removed desktop file: {desktop_file}")

    for name in service_names:
        service_file = user_systemd_dir / f"{name}.service"
        if service_file.exists():
            print(f"Uninstalling {name} service...")
            try:
                subprocess.run(
                    ["systemctl", "--user", "disable", "--now", name], check=False
                )
                service_file.unlink()
                print(f"Removed unit file: {service_file}")
            except Exception as e:
                print(f"Error during uninstalling {name}: {e}")

    subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
    print("\nSuccessfully uninstalled daemon services.")


def main():
    parser = argparse.ArgumentParser(
        description="Push-to-Whisper: Key-hold voice memos with Whisper"
    )
    parser.add_argument(
        "-v", "--version", action="version", version=f"%(prog)s {__version__}"
    )
    parser.add_argument("-c", "--config", type=Path, help="Path to config file")

    subparsers = parser.add_subparsers(dest="command", help="Subcommands")

    # serve command
    serve_parser = subparsers.add_parser("serve", help="Start the daemon")
    serve_parser.set_defaults(func=serve_action)

    # init command
    init_parser = subparsers.add_parser("init", help="Initialize configuration")
    init_parser.add_argument("-o", "--output", type=str, help="Output file path")
    init_parser.add_argument(
        "--bare", action="store_true", help="Output default values only"
    )
    init_parser.set_defaults(func=init_action)

    # install-daemon command
    install_parser = subparsers.add_parser(
        "install-daemon", help="Install systemd user service"
    )
    install_parser.set_defaults(func=install_daemon_action)

    # uninstall-daemon command
    uninstall_parser = subparsers.add_parser(
        "uninstall-daemon", help="Uninstall systemd user service"
    )
    uninstall_parser.set_defaults(func=uninstall_daemon_action)

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(0)

    args.func(args)


if __name__ == "__main__":
    main()
