import logging
import re
from pathlib import Path
from typing import Optional

import patch_ng
from any_llm import completion

logger = logging.getLogger(__name__)


class LLMClient:
    def __init__(self, settings):
        self.settings = settings

    def refine_text(
        self, text: str, mode: str = "refine", prompt_override: Optional[str] = None
    ) -> str:
        """Refine and format text using any-llm"""
        if not self.settings.llm.model:
            return text

        system_prompt = prompt_override
        if not system_prompt:
            system_prompt = (
                self.settings.defaults.llm_refine.get("system_prompt")
                if mode == "refine"
                else self.settings.defaults.llm_instruction.get("system_prompt")
            )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": text},
        ]

        kwargs = {
            "model": self.settings.llm.model,
            "messages": messages,
            "api_key": self.settings.llm.api_key,
            "api_base": self.settings.llm.base_url,
        }
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        try:
            response = completion(**kwargs)
            refined_text = response.choices[0].message.content.strip()
            return refined_text
        except Exception as e:
            logger.error(f"LLM error during refinement: {e}")
            return text

    def generate_patch(self, instruction: str, current_content: str) -> str:
        """Generate a patch in udiff format using any-llm"""
        if not self.settings.llm.model:
            return ""

        system_prompt = self.settings.defaults.llm_patch.get("system_prompt")

        messages = [
            {"role": "system", "content": system_prompt},
            {
                "role": "user",
                "content": f"## Instruction\n{instruction}\n\n## Target Content\n{current_content}",
            },
        ]

        kwargs = {
            "model": self.settings.llm.model,
            "messages": messages,
            "api_key": self.settings.llm.api_key,
            "api_base": self.settings.llm.base_url,
        }
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        try:
            response = completion(**kwargs)
            patch_text = response.choices[0].message.content.strip()

            # Remove Markdown code blocks (```diff ... ```) if present
            patch_text = re.sub(r"^```(diff)?\n", "", patch_text)
            patch_text = re.sub(r"\n```$", "", patch_text)

            logger.debug(f"Generated Patch:\n{patch_text}")

            return patch_text
        except Exception as e:
            logger.error(f"LLM error: {e}")
            return ""

    def apply_patch(self, target_file: Path, patch_text: str) -> bool:
        """Apply the generated patch to the file"""
        if not patch_text:
            return False

        try:
            # Depending on the environment, patch-ng might need to be imported as patch_ng
            pset = patch_ng.fromstring(patch_text.encode("utf-8"))
            if not pset:
                logger.error("Failed to parse patch text.")
                return False

            # Force filenames in the patch to match the target file.
            # This allows application even if the filename generated by LLM differs.
            for p in pset:
                p.source = p.target = target_file.name.encode("utf-8")

            # pset.apply expects a file object or list.
            # Using patch-ng features here for simplicity.
            success = pset.apply(0, root=str(target_file.parent), fuzz=True)

            if success:
                logger.info(f"Successfully applied patch to {target_file}")
                return True
            else:
                logger.error(f"Failed to apply patch to {target_file}")
                return False

        except Exception as e:
            logger.error(f"Patch application error: {e}")
            return False
