from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional


@dataclass
class PipelineState:
    """
    Shared execution state for the entire pipeline (data flow container).
    Each step reads from and writes to this object to pass data.
    """

    # --- Basic Input Info ---
    audio_path: Path
    pipeline_id: str
    start_time: datetime = field(default_factory=datetime.now)

    # --- Processing Results (Filled by steps) ---
    whisper_text: str = ""  # Original transcription from Whisper
    refined_text: str = ""  # Text refined by LLM
    instruction_result: str = ""  # Result from LLM instruction mode
    patch_result: str = ""  # Patch (udiff) generated by LLM

    # --- Metadata ---
    audio_duration: float = 0.0
    processing_time_sec: float = 0.0
    text_path: Optional[Path] = None  # Path to the saved Markdown file
    rendered_content: str = ""  # Full rendered Markdown content

    # --- Data for Templates ---
    # Steps append "content to be displayed to user" here
    display_sections: Dict[str, str] = field(default_factory=dict)

    # Documentation for available template variables (for auto-docs)
    VARIABLE_DOCS = {
        "date_iso": "Execution date/time in ISO 8601 format (YYYY-MM-DDTHH:MM:SS)",
        "date": "Execution date (YYYYMMDD)",
        "time": "Execution time (HHMMSS)",
        "start_time": "The datetime object of when the recording/processing started (use for custom formatting like {{ start_time.strftime('%Y-%m-%d') }})",
        "audio_file_name": "Name of the recorded audio file (e.g., memo.wav)",
        "markdown_file_name": "Name of the saved Markdown file (N/A if not saved)",
        "duration_sec": "Duration of the audio in seconds",
        "processing_time_sec": "Total pipeline processing time in seconds",
        "speed_ratio": "Processing speed ratio (audio duration / processing time)",
        "full_text": "Raw transcription result from Whisper",
        "refined_text": "Refined text from LLM (llm_refine step)",
        "instruction_result": "Result from LLM instruction mode (llm_instruction step)",
        "rendered_content": "The full rendered Markdown content (available after save_markdown step)",
    }

    def to_template_vars(self) -> Dict[str, Any]:
        """Generate a dictionary for template engines (Markdown, Apprise, etc.)."""
        # Explicitly organize available variables
        vars = {
            "date_iso": self.start_time.isoformat(),
            "date": self.start_time.strftime("%Y%m%d"),
            "time": self.start_time.strftime("%H%M%S"),
            "start_time": self.start_time,  # datetime object at start
            "audio_file_name": self.audio_path.name,
            "markdown_file_name": self.text_path.name if self.text_path else "N/A",
            "duration_sec": self.audio_duration,
            "processing_time_sec": self.processing_time_sec,
            "speed_ratio": (
                self.audio_duration / self.processing_time_sec
                if self.processing_time_sec > 0
                else 0.0
            ),
            "full_text": self.whisper_text,
            "refined_text": self.refined_text,
            "instruction_result": self.instruction_result,
            "rendered_content": self.rendered_content,
            # Expand display_sections as-is
            **self.display_sections,
        }
        return vars
